export {LoadingScreen as LoadingContainer} from './Loading'
export {LoginScreen as LoginContainer} from './Login'
export {ForgotPassword as ForgotPassContainer} from './ForgotPass'
export {DefaultSettings as DefaultSettingsContainer} from './DefaultSettings'
export {ChangePassword as ChangePasswordConatiner} from './ChangePassword'